$(function(){"use strict";var allWindow=$(window),body=$('body'),top=allWindow.scrollTop(),navBar=$(".nav-wrapper");allWindow.on("load",function(){$('.loader-con').fadeOut('slow')});var animation=!1,animationstring='animation',keyframeprefix='',domPrefixes='Webkit Moz O ms Khtml'.split(' '),pfx='',elm=document.createElement('div');if(elm.style.animationName!==undefined){animation=!0}
if(animation===!1){for(var i=0;i<domPrefixes.length;i++){if(elm.style[domPrefixes[i]+'AnimationName']!==undefined){pfx=domPrefixes[i];animationstring=pfx+'Animation';keyframeprefix='-'+pfx.toLowerCase()+'-';animation=!0;break}}}
jQuery.scrollSpeed=function(step,speed){var $document=$(document),$body=$('html, body'),option='default',root=top,scroll=!1,scrollY,view;if(window.navigator.msPointerEnabled){return!1}
jQuery.event.special.mousewheel={setup:function(_,ns,handle){if(ns.includes("PreventDefault")){this.addEventListener("mousewheel",handle,{passive:!1})}else{return!1}}}
allWindow.on('mousewheel.PreventDefault DOMMouseScroll',function(e){var deltaY=e.originalEvent.wheelDeltaY,detail=e.originalEvent.detail;scrollY=$document.height()>allWindow.height();scroll=!0;if(scrollY){view=allWindow.height();if(deltaY<0||detail>0){root=(root+view)>=$document.height()?root:root+=step}
if(deltaY>0||detail<0){root=root<=0?0:root-=step}
$body.stop().animate({scrollTop:root},speed,option,function(){scroll=!1})}
return!1}).on('scroll',function(){if(scrollY&&!scroll)root=top;if(!scroll)root=allWindow.scrollTop()}).on('resize',function(){if(scrollY&&!scroll)view=allWindow.height()})};jQuery.easing.default=function(x,t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b};if(animation){jQuery.scrollSpeed(100,700)}
function stikyNav(){top=allWindow.scrollTop();if(top>=100){navBar.addClass("nav-sticky")}else{navBar.removeClass("nav-sticky")}
if(top>=1000){$('.scroll-up').addClass("show-up-btn")}else{$('.scroll-up').removeClass("show-up-btn")}}
$('a.scroll').on('click',function(event){if(location.pathname.replace(/^\//,'')===this.pathname.replace(/^\//,'')&&location.hostname===this.hostname){var target=$(this.hash),speed=$(this).data("speed")||800;target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){event.preventDefault();$('html, body').animate({scrollTop:target.offset().top},speed)}}});$(".scroll-up").on('click',function(e){e.preventDefault();$('html, body').animate({scrollTop:0},900)});var navLinks=navBar.find(".navbar-collapse ul li a");$.each(navLinks,function(i,val){var navLink=$(this);navLink.on('click',function(e){navBar.find(".navbar-collapse").collapse('hide')})});var sections=$('.one-page-section'),navList=navBar.find("ul.navbar-nav");function ChangeClass(){top=allWindow.scrollTop();$.each(sections,function(i,val){var section=$(this),section_top=section.offset().top-10,bottom=section_top+section.height();if(top>=section_top&&top<=bottom){var naItems=navList.find('li');$.each(naItems,function(i,val){var item=$(this);item.find("a").removeClass("active")});navList.find('li [href="#'+section.attr('id')+'"]').addClass('active')}})}
var backgrounds=$('.parallax');function parallax(){$.each(backgrounds,function(i,val){var backgroundObj=$(this),backgroundObjTop=backgroundObj.offset().top,backgroundHeight=backgroundObj.height();top=allWindow.scrollTop();var yPos=((top-backgroundObjTop))/2;if(yPos<=backgroundHeight+backgroundObjTop){backgroundObj.css({backgroundPosition:'50% '+yPos+'px'})}})};var linesHead=$(".skills-section"),line=$(".progress-bar-line");function progressFunction(e){if(linesHead.length){if(!linesHead.hasClass("done")){var linesHeadTop=linesHead.offset().top,top=allWindow.scrollTop(),winH=allWindow.height()-160;if(top>=linesHeadTop-winH){linesHead.addClass("done");$.each(line,function(i,val){var thisLine=$(this),value=thisLine.data("percent"),progressCont=$(thisLine).closest('.progress-bar-linear').find(".progress-cont span");thisLine.css("width",value+"%");progressCont.html(value+"%")})}}}}
function scrollFunctions(){stikyNav();ChangeClass();parallax();progressFunction()}
allWindow.on('scroll',function(){scrollFunctions()});if(animation){var text=$('#home .typer-title'),textOne="I'm a member of Robotics club",textTwo="let's work together",textThree="i can create awesome stuff";if(!!$.prototype.typer){text.typer([textOne,textTwo,textThree])}}
if(typeof particlesJS!=="undefined"){particlesJS('particles-js',{"particles":{"number":{"value":80,"density":{"enable":!0,"value_area":600}},"color":{"value":'#777',},"shape":{"type":"circle","stroke":{"width":0,"color":"#888"},"polygon":{"nb_sides":5},"image":{"src":"img/github.svg","width":100,"height":100}},"opacity":{"value":0.7,"random":!1,"anim":{"enable":!1,"speed":1,"opacity_min":0.1,"sync":!1}},"size":{"value":4,"random":!0,"anim":{"enable":!1,"speed":40,"size_min":0.1,"sync":!1}},"line_linked":{"enable":!0,"distance":150,"color":"#bbb","opacity":0.4,"width":1},"move":{"enable":!0,"speed":4,"direction":"bottom","random":!1,"straight":!1,"out_mode":"out","attract":{"enable":!1,"rotateX":600,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":!0,"mode":"repulse"},"onclick":{"enable":!0,"mode":"push"},"resize":!0},"modes":{"grab":{"distance":400,"line_linked":{"opacity":1}},"bubble":{"distance":400,"size":40,"duration":2,"opacity":8,"speed":3},"repulse":{"distance":200},"push":{"particles_nb":4},"remove":{"particles_nb":2}}},"retina_detect":!0,"config_demo":{"hide_card":!1,"background_color":"#b61924","background_image":"","background_position":"50% 50%","background_repeat":"no-repeat","background_size":"cover"}})}
var FilterContainer=$('#work .filtr-container');if(FilterContainer.length>0&&!!$.prototype.isotope){var filterizd;FilterContainer.imagesLoaded(function(){filterizd=FilterContainer.isotope({itemSelector:'.filtr-item',})});$('#work-list li a.filter').on('click',function(e){e.preventDefault();var target=$(this),filterValue=target.data('filter');filterizd.isotope({filter:filterValue});if(!target.hasClass("filter-active")){$('#work-list').find('.filter-active').removeClass('filter-active');target.addClass('filter-active')}})}
$(".popup-youtube").magnificPopup({type:'iframe'});$('.popup-link').magnificPopup({type:'image',removalDelay:300,mainClass:'mfp-fade',gallery:{enabled:!0},zoom:{enabled:!0,duration:260,easing:'ease-in',}});if(!!$.prototype.owlCarousel){$(".home-3 .home-carousel").owlCarousel({nav:!0,navText:["<div class='home-slider-btn effect ver-center'><i class='fa fa-chevron-left center'></i><span></span></div>","<div class='home-slider-btn effect ver-center'><i class='fa fa-chevron-right center'></i><span></span></div>"],dots:!0,loop:!0,items:1,});$(".testimonial-slider").owlCarousel({loop:!0,nav:!0,navText:["<div class='testimonial-slider-btn effect hor-center'><i class='fa fa-angle-left center'></i></div>","<div class='testimonial-slider-btn effect hor-center'><i class='fa fa-angle-right center'></i></div>"],margin:20,responsive:{0:{items:1,},780:{items:2,},}})}
var form=$('#contact-form'),reg=/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{3,4})$/,inputs=$(".input-field");function validateForm(){if($(this).is("#email")){var email=$(this).val(),res=reg.test(email);if(res){$(".email-error").html("")}else{$(".email-error").html("please enter a valid email.");return!1}}else{var target=($(this).attr("id")),targetMessage=$("."+target+"-error");if($(this).val()===""){targetMessage.html("please enter a valid "+target+".");return!1}else{targetMessage.html(" ")}}}
$.each(inputs,function(i,val){$(this).on("blur",validateForm)});var formMessages=$('#form-message');$(form).on('submit',function(event){event.preventDefault();var formData=$(form).serialize();$.ajax({type:'POST',url:form.attr('action'),data:formData}).done(function(response){formMessages.removeClass('error');formMessages.addClass('success');formMessages.text(response);$('#name').val('');$('#email').val('');$('#message').val('')}).fail(function(data){formMessages.removeClass('success');formMessages.addClass('error');if(data.responseText!==''){formMessages.text(data.responseText)}else{formMessages.text('Sorry! An error occured and your message could not be sent.')}})})})
